# -*- coding: utf-8 -*-
"""assignment_3_day_8_july_2020_rajakuamran1630.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mJ2rUnL1S-BJGQR-wu3FolJ_ZgXZ7sS3

# **Question 1 :**
Write a program to subtract two complex numbers in Python
"""

a=20
b=30
c=b-a
print(c)

"""## **Question 2 :**
Write a program to find the fourth root of a number.
"""

x=625
z=x**(1/4)
print(x," of the fourth root: ",z)

"""## **Question 3:**
Write a program to swap two numbers in Python with the help of a temporary variable.
"""

a=20
b=30
print("Before Swapping: a =", a, " b =", b); 
c=a
a=b
b=c
print("After Swapping: a =", a, " b =", b);

"""## **Question 4:**
Write a program to swap two numbers in Python without using a temporary variable.
"""

x = 10
y = 5
print("Before Swapping: x =", x, " y =", y); 

# Code to swap 'x' and 'y' 
  
# x now becomes 15 
x = x + y   
  
# y becomes 10 
y = x - y  
  
# x becomes 5 
x = x - y   
print("After Swapping: x =", x, " y =", y);

"""## **Question 5:**
Write a program to convert fahrenheit to kelvin and celsius both.
"""



"""## **Question 6:** 
Write a program to demonstrate all the available data types in Python. Hint: Use type() function
"""



"""### **Question 7**: 
Create a Markdown cell in jupyter and list the steps discussed in the session by Dr. Darshan Ingle sir to create Github profile and upload Githubs Assignment link
"""

